Check that setScriptSource completes correctly when an exception is thrown.

Running test: testIncorrectScriptId
{
    error : {
        code : -32000
        message : Uncaught Script not found
    }
    id : <messageId>
}

Running test: testSourceWithSyntaxError
{
    id : <messageId>
    result : {
        exceptionDetails : {
            columnNumber : 2
            exceptionId : <exceptionId>
            lineNumber : 0
            text : Invalid or unexpected token
        }
    }
}
